.TH ft_ls 1 "March 20, 2016" "IN DEVELOPMENT" "ft_ls : UNIX branch @ 42"
.SH NAME
ft_ls \- list files details
.SH SYNOPSIS
.B ft_ls
[\-aArlhgRt] [files ...]
.SH DESCRIPTION
Print fi

.PP
.SH OPTIONS
\-l 	Print in long format
.PP
\-h 	In long format, show sizes in larger units than bytes. !! NOT THE EXACT VALUE FOR THE MOMENT
.PP
\-a 	Show all (hidden too) files
.PP
\-A 	Show all files, except '.' and '..'
.PP
\-R 	Recursively search folders
.PP
